#database password

base:
  DB_PASSWORD: caWRlV78KHmgvKxd
  DB_URL: mongodb://thanhng_admin:caWRlV78KHmgvKxd@cluster0-shard-00-00-uln9r.mongodb.net:27017,cluster0-shard-00-01-uln9r.mongodb.net:27017,cluster0-shard-00-02-uln9r.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin